### ISSUE TITLE
VR view is not correctly aligned sometimes when loading a game

### ISSUE THREAD

**Issue by ThndrDev** [ThndrDev/StationeersVR#5]
Needs to trigger  a recenter when the VR player gets attached

**Comment by ihatetn931** [comment]
I did my best to fix this issue, but if a recenter hits and your head is not straight it will align to that view. So the alignment mostly depends on the user being in the position they want, but they also have the Y button which will recenter at anytime, which I plan on adding a button to the pause menu to re center as well.
